### ISSUE TITLE
Feature request: Add ability to track multiple different objects. and give those objects different ID values easily. 

### ISSUE THREAD

**Issue by villimikko** [sujanshresstha/sam2-in-video#2]
Also make possible to add trackable objects in middle of the video as well.

**Comment by sujanshresstha** [comment]
Hi @villimikko ,
Thank you for your feature request regarding the ability to track multiple different objects, as well as the capability to add trackable objects in the middle of the video.
I have  implemented requrested features in the latest version of the repository. Here are the key updates:

- [x] Multiple Object Tracking: You can now track multiple objects simultaneously, each with a unique ID. This allows for more complex and detailed video analysis.

- [x] Dynamic Object Addition: It is now possible to add new trackable objects at any point during the video. This feature provides greater flexibility and control over the tracking process.

Thank you for your valuable feedback and support!
Best regards,
